name: com_client
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=2.18.0-271.4.beta <3.0.0'

dependencies:
  com:
    #path: ../com
    git:
       url: https://github.com/Marc-R2/com.git
       ref: stable # connector_for_client_devices
  com_auth_service_dart:
    # path: ../com_auth_service_dart
    git:
      url: https://github.com/Marc-R2/com_auth_service_dart.git

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  very_good_analysis: ^3.1.0
