name: com_client
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  com:
    #path: ../com
    git:
       url: https://github.com/Marc-R2/com.git
       # ref: stable # connector_for_client_devices

dev_dependencies:
  lints: ^2.0.0
  mutation_test: ^1.3.1
  test: ^1.21.5
  very_good_analysis: ^3.0.1
