import 'package:com/com_client.dart';

class PublicAuthService {
  static const data = ServiceData(
    name: 'auth',
    version: '0.0.1',
    authLevel: AuthLevel.public,
    devLevel: DevLevel.stable,
    secureLevel: SecureLevel.none,
  );

  static const device = TaskData(
    name: 'device',
    parent: data,
  );
}

class PublicDeviceTask {
  /// Key-String generated by the client
  static const deviceKey = DataType<String>(name: 'deviceKey');

  /// ID-String generated by the server
  static const deviceID = DataType<String>(name: 'deviceID');

  /// Register a device
  static const registerDevice = FieldData<String>(
    name: 'registerDevice',
    args: [deviceKey],
    parent: PublicAuthService.device,
  );

  /// Create a session for a device
  static const createSession = FieldData<String>(
    name: 'createSession',
    args: [deviceID, deviceKey],
    parent: PublicAuthService.device,
  );
}
