import 'package:com/com_client.dart';

class PublicDeviceTask {
  /// Key-String generated by the client
  static const deviceKey = DataType<String>(name: 'deviceKey');

  /// ID-String generated by the server
  static const deviceID = DataType<String>(name: 'deviceID');

  /// Register a device
  static const registerDevice = FieldData<String>(
    name: 'registerDevice',
    args: [deviceKey],
  );

  /// Create a session for a device
  static const createSession = FieldData<String>(
    name: 'createSession',
    args: [deviceID, deviceKey],
  );
}
